services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: geov0-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./.qdrant/storage:/qdrant/storage
    restart: unless-stopped
